# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: App Test / Install / Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_tests:

    runs-on: ubuntu-latest

    steps:
    - name: clone the app Repository
      uses: actions/checkout@v4
    - name: Use Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: install NPM
      run: npm install
    - name: Run NPM tests
      run: npm run test
   

  Start_App:

    runs-on: ubuntu-latest
    needs: build_tests
    steps:
    - name: clone the app Repository
      uses: actions/checkout@v4
    - name: Use Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: install NPM
      run: npm install
    - name: Run NPM tests
      run: npm run test
    - name: Start NPM Application
      run: npm run start &   

 
  Deploy_App_To_Render:
    runs-on: ubuntu-latest
    needs: Start_App
    steps:
      - name: Deploy to production
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.SERVICE_ID }}
          api-key: ${{ secrets.RENDER_API_KEY }}
          wait-for-success: true